# --- !Ups

CREATE TABLE "ACCOUNT" (
  "ID"     INTEGER     NOT NULL AUTO_INCREMENT PRIMARY KEY,
  "BALANCE"  INTEGER     NOT NULL,
  "DEP_COUNT"  INTEGER     NOT NULL,
  "WITHDRAW_COUNT"  INTEGER     NOT NULL,
  "DEP_UPDATED"  VARCHAR(50) NOT NULL,
  "WITHDRAW_UPDATED"  VARCHAR(50) NOT NULL
);
INSERT INTO "ACCOUNT" VALUES (1, 0, 0, 0, '', '');

# --- !Downs
DROP TABLE "ACCOUNT" IF EXISTS;


